monolog:
    handlers:
        error_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/error.log"
            level: error
            channels: ["!event"]
            max_files: 10

        info_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/info.log"
            level: info
            max_files: 10

        debug_log:
               type:  stream
               path:  "%kernel.logs_dir%/%kernel.environment%/debug.log"
               level: debug
               channels: ["!event", "!doctrine", "!console", "!request", "!security", '!php']
               max_files: 10

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
#channels doctrine, event, security, request, console